data:
    dataset: 'FLIR_ADAS'
    filepath: '../datasets/FLIR_ADAS/video/PreviewData/'
    preprocessing:
        resize: [256, 320]
    gaussian_label:
        enable: false
front_end_model: 'Val_model_heatmap'  # 'Train_model_heatmap'
model:
    name: 'SuperPointNet_gauss2' # SuperPointNet_heatmap
    params: {}
    detection_threshold: 0.015
    nms: 4
    nn_thresh: 1.0
    subpixel: 
        enable: true
        patch_size: 5
    pretrained: 'logs/superpoint_flir/checkpoints/superPointNet_58000_checkpoint.pth.tar'
    batch_size: 1