feature: 'superpoint'
data:
    dataset: 'FLIR_ADAS'
    filepath: '../datasets/kitti/data_odometry_gray/dataset/sequences/03/image_0/'
    storagepath: '../datasets/kitti/data_odometry_gray/dataset/sequences/03/RGB_Feat_and_Descriptors/'
    for_vocab: false
    preprocessing:
        resize: [368, 1240]
    gaussian_label:
        enable: false
front_end_model: 'Val_model_heatmap'  # 'Train_model_heatmap'
model:
    name: 'SuperPointNet_gauss2' # SuperPointNet_heatmap
    params: {}
    detection_threshold: 0.015
    nms: 4
    nn_thresh: 1.0
    subpixel: 
        enable: true
        patch_size: 5
    pretrained: 'logs/superpoint_coco_heat2_0/checkpoints/superPointNet_170000_checkpoint.pth.tar'
    batch_size: 1