data:
    dataset: 'FLIR_ADAS'
    filepath: '../datasets/vivid/indoor_robust_local_data/images/' #'../datasets/FLIR_ADAS/train/Data_CLAHE_AGC/'
    storagepath: '../datasets/vivid/indoor_robust_local_data/Keypts_and_Desc/' #'../datasets/FLIR_ADAS/train/Keypts_and_Desc/'
    for_vocab: false #true
    gaussian_label:
        enable: false
front_end_model: 'Val_model_heatmap'  # 'Train_model_heatmap'
model:
    name: 'SuperPointNet_gauss2' # SuperPointNet_heatmap
    params: {}
    detection_threshold: 0.015
    nms: 4
    nn_thresh: 1.0
    subpixel: 
        enable: true
        patch_size: 5
    pretrained: 'logs/superpoint_flir_clahe/checkpoints/superPointNet_46000_checkpoint.pth.tar'
    batch_size: 1